#1 documentation
smirnovV/find-max pull request #2
Opened 2018-06-08 08:59 UTC by smirnovV

2018-06-08 10:06 UTC, 01sas commented on src/main/java/ru/smirnovv/FindMax.java
> +     * @param args the arguments for program
Please add the description for the method itself, not only for arguments, like "The entry point.".

2018-06-08 10:06 UTC, 01sas commented on src/main/java/ru/smirnovv/FindMax.java
> +     * @param args the arguments for program
Please put a dot the end of the line.

2018-06-08 10:06 UTC, 01sas commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> +     * @param maxSize the maximum number of elements
Please put a dot at the end of the line.

2018-06-08 10:06 UTC, 01sas commented on src/main/java/ru/smirnovv/FindMax.java
>  import static picocli.CommandLine.*;
Plese, avoid using of wildcard import.

2018-06-08 10:06 UTC, 01sas commented on src/main/java/ru/smirnovv/FindMax.java
> + * Program for find the given number of maximums.
"Program that finds the given number of maximums."

2018-06-08 10:40 UTC, aanbrn commented on src/main/java/ru/smirnovv/FindMax.java
>          version = "FindMax 0.1.0")
Would be great to replace the name and version attributes with "${project.artifactId}" and "${project.version}" accordingly and to enable filtering of java source files in Maven that will place the actual artifactId and version into the attribute values. Another way is just to add the version info into the Manifest file and to implement IVersionProvider from Picocli that should extract the version info from the Manifest file in runtime.

2018-06-08 10:44 UTC, aanbrn commented on src/main/java/ru/smirnovv/FindMax.java
> + * Program for find the given number of maximums.
Finds the given number of maximums reading lines from the standard input.

2018-06-08 10:45 UTC, aanbrn commented on src/main/java/ru/smirnovv/FindMax.java
> +     * The number of elements for print.
The number of maximums to find.

2018-06-08 10:47 UTC, aanbrn commented on src/main/java/ru/smirnovv/FindMax.java
> +     * @param args the arguments for program
Yeah, for example, The entry point. And use "the program arguments" for args.

2018-06-08 10:56 UTC, aanbrn commented on src/main/java/ru/smirnovv/FindMax.java
> +     * Method, where read lines and print maximum numbers.
Executes the program flow reading lines from the standard input, finding maximum numbers in them and printing the result to the standard output.

2018-06-08 10:58 UTC, aanbrn commented on src/main/java/ru/smirnovv/FindMax.java
> +     * @throws IOException if the BufferedReader throws IOException
if an IO error occurred.

2018-06-08 11:04 UTC, aanbrn commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> + * MaxBoundedTreeSet extends the <tt>TreeSet</tt> class.
A bounded TreeSet of Long numbers limited by the maximum size and intended to collect the maximum elements.

2018-06-08 11:05 UTC, aanbrn commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> +     * The maximum number of elements in the MaxBoundedTreeSet.
The maximum number of elements in this set.

2018-06-08 11:05 UTC, aanbrn commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> +     * Constructs an empty MaxBoundedTreeSet with the specified
Constructs an instance with the given maximum size.

2018-06-08 11:06 UTC, aanbrn commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> +     * @param maxSize the maximum number of elements
the maximum size.

2018-06-08 11:06 UTC, aanbrn commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> +     * @throws IllegalArgumentException if the specified maximum number
if 'maxSize' is not positive.

2018-06-08 11:15 UTC, aanbrn commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> +     * Adds the specified element to this set if this element greater
Adds a new number to this set if it's not full yet or if the given number is greater than the smallest one in it. When this set is full already and the given number added, it removes the smallest one to keep the maximum size.

2018-06-08 11:15 UTC, aanbrn commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> +     * @param e element to be added to this set
a number to be added.

2018-06-08 11:16 UTC, aanbrn commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> +     * @return {@code true} if element added to the MaxBoundedTreeSet
whether the given number added to this set or not.

2018-06-08 11:16 UTC, aanbrn commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> +     * @throws NullPointerException if the specified element is null
if the given number is null.

2018-06-08 11:17 UTC, aanbrn commented on src/main/java/ru/smirnovv/MaxBoundedTreeSet.java
> -    public boolean add(/*@NotNull*/final Long e) {
Let's rename e to n.

2018-06-08 11:32 UTC, aanbrn commented on src/main/java/ru/smirnovv/MyCollectors.java
> + * This class contains methods, that returns new collectors.
A utility class containing factory-methods for own collectors.

2018-06-08 11:32 UTC, aanbrn commented on src/main/java/ru/smirnovv/MyCollectors.java
> +     * Don't let anyone instantiate this class.
Private constructor to block instantiation.

2018-06-08 11:35 UTC, aanbrn commented on src/main/java/ru/smirnovv/MyCollectors.java
> +     * Return the new collector described by the MaxBoundedTreeSet methods.
Returns a collector that accumulates the input elements into a bounded set of maximum ones.

2018-06-08 11:36 UTC, aanbrn commented on src/main/java/ru/smirnovv/MyCollectors.java
> +     * @param numberOfMaxes the number of elements for initialization
Let's rename numberOfMaxes to numberOfMaximums.

2018-06-08 11:38 UTC, aanbrn commented on src/main/java/ru/smirnovv/MyCollectors.java
> +     * @param numberOfMaxes the number of elements for initialization
the maximum number of maximum elements.

2018-06-08 11:38 UTC, aanbrn commented on src/main/java/ru/smirnovv/MyCollectors.java
> +     * @throws IllegalArgumentException if the specified number of maxes
if 'numberOfMaximums' is not positive.

2018-06-08 11:42 UTC, aanbrn requested changes
Please take a look at my comments.

2018-06-18 06:45 UTC, 01sas approved these changes

2018-06-18 07:43 UTC, aanbrn requested changes
See my new comments.

2018-06-18 07:43 UTC, aanbrn commented on src/main/java/ru/smirnovv/FindMax.java
> +            Manifest manifest = new Manifest(url.openStream());
Probably better to close the opened stream.

2018-06-18 07:43 UTC, aanbrn commented on src/main/java/ru/smirnovv/FindMax.java
> +            return new String[]{implVersion};
Doesn't look formatted.

2018-06-18 07:43 UTC, aanbrn commented on src/main/java/ru/smirnovv/FindMax.java
> +    public static class VersionProvider implements CommandLine.IVersionProvider {
Where is javadoc?

2018-06-18 07:43 UTC, aanbrn commented on src/main/java/ru/smirnovv/MyCollectors.java
> +    public static Collector<Long, MaxBoundedTreeSet, MaxBoundedTreeSet> maxN(/*@Nonnegative*/ final int numberOfMaximums) {
This line looks quite long and probably needs to be formatted.

2018-06-18 11:21 UTC, 01sas approved these changes

2018-06-18 11:31 UTC, aanbrn approved these changes

2018-06-19 09:42 UTC, closed without merging